Update kernel spec files from upstream

diff --git a/rpm/kernel-binary.spec.in b/rpm/kernel-binary.spec.in
--- a/rpm/kernel-binary.spec.in
+++ b/rpm/kernel-binary.spec.in
@@ -28,14 +28,16 @@
 
 %define build_flavor	@FLAVOR@
 %define build_default	("%build_flavor" == "default")
-%define build_xen	("%build_flavor" == "xen" || "%build_flavor" == "ec2")
 %define build_vanilla	("%build_flavor" == "vanilla")
 
-%define build_src_dir %my_builddir/linux-%srcversion
+%if ! %build_vanilla
 %define src_install_dir /usr/src/linux-%kernelrelease%variant
-%define obj_install_dir %src_install_dir-obj
+%else
+%define src_install_dir /usr/src/linux-%kernelrelease-vanilla
+%endif
+%define obj_install_dir /usr/src/linux-%kernelrelease%variant-obj
 %define rpm_install_dir %buildroot%obj_install_dir
-%define kernel_build_dir %build_src_dir/linux-obj
+%define kernel_build_dir %my_builddir/linux-%srcversion/linux-obj
 
 %(chmod +x %_sourcedir/{@SCRIPTS@})
 
@@ -44,7 +46,7 @@
 
 # Define some CONFIG variables as rpm macros as well. (rpm cannot handle
 # defining them all at once.)
-%define config_vars CONFIG_MODULES CONFIG_MODULE_SIG CONFIG_KMSG_IDS CONFIG_SPLIT_PACKAGE CONFIG_SUSE_KERNEL_SUPPORTED CONFIG_EFI_STUB
+%define config_vars CONFIG_MODULES CONFIG_MODULE_SIG CONFIG_MODULE_SIG_KEY CONFIG_KMSG_IDS CONFIG_SPLIT_PACKAGE CONFIG_SUSE_KERNEL_SUPPORTED CONFIG_EFI_STUB
 %{expand:%(eval "$(test -n "%cpu_arch_flavor" && tar -xjf %_sourcedir/config.tar.bz2 --to-stdout config/%cpu_arch_flavor)"; for config in %config_vars; do echo "%%global $config ${!config:-n}"; done)}
 %define split_base (%CONFIG_SPLIT_PACKAGE == "y")
 %define split_extra (%CONFIG_SPLIT_PACKAGE == "y" && %CONFIG_SUSE_KERNEL_SUPPORTED == "y")
@@ -72,9 +74,11 @@ BuildRequires:  fdupes
 %if 0%{?suse_version} > 1310
 BuildRequires:  hmaccalc
 %endif
+BuildRequires:  libopenssl-devel
 BuildRequires:  modutils
 # Used to sign the kernel in the buildservice
-BuildRequires:  pesign-obs-integration openssl
+BuildRequires:  openssl
+BuildRequires:  pesign-obs-integration
 Provides:       %name = %version-%source_rel
 # bnc#901925
 Provides:       %name-%version-%source_rel
@@ -82,8 +86,13 @@ Provides:       %{name}_%_target_cpu = %version-%release
 Provides:       multiversion(kernel)
 %if %split_base
 Provides:       kernel-base = %version-%source_rel
-# Obsolete the -base subpackage from 11.1 and 11.2 development phase
-Obsoletes:      %name-base <= 2.6.31
+# In SLE11, kernel-$flavor complemented kernel-$flavor-base. With SLE12,
+# kernel-$flavor itself contains all the needed files and kernel-$flavor-base
+# is a subset that can replace kernel-$flavor in some scenarios. We need to
+# obsolete the -base subpackage from SLE11, so that the base files are not
+# owned by multiple packages now. The dependency is not correct wrt openSUSE
+# 11.2 - 11.4, but we primarily care about the supported upgrade path.
+Obsoletes:      %name-base < 3.1
 %endif
 Requires(pre):  coreutils awk
 # For /usr/lib/module-init-tools/weak-modules2
@@ -122,16 +131,13 @@ BuildRequires:  dwarfextract
 %ifarch %arm
 BuildRequires:  u-boot-tools
 %endif
-%if %build_xen
-#!BuildIgnore:  xen
-%endif
 
 Obsoletes:      microcode_ctl
 
-%if %build_vanilla
-# force bzip2 instead of lzma compression to allow install on older dist versions
+# Force bzip2 instead of lzma compression to
+# 1) allow install on older dist versions, and
+# 2) decrease build times (bsc#962356)
 %define _binary_payload w9.bzdio
-%endif
 # dead network if installed on SLES10, otherwise it will work (mostly)
 Conflicts:      sysfsutils < 2.0
 Conflicts:      apparmor-profiles <= 2.1
@@ -146,6 +152,8 @@ Conflicts:      libc.so.6()(64bit)
 %endif
 Provides:       kernel = %version-%source_rel
 @PROVIDES_OBSOLETES@
+@PROVIDES_OBSOLETES_BASE@
+%obsolete_rebuilds %name
 @SOURCES@
 BuildRoot:      %{_tmppath}/%{name}-%{version}-build
 ExclusiveArch:  @ARCHS@
@@ -185,8 +193,6 @@ Provides: %1-kmp-%build_flavor = %2
 %obsolete_kmp perfmon 2_3
 %obsolete_kmp iwlagn-2-6-27 1.0_3
 %obsolete_kmp msi-wmi 1.0_3
-# sle11
-%obsolete_kmp ocfs2 1.6_4
 # 11.1
 %obsolete_kmp quickcam 0.6.7
 # sle11-sp1
@@ -211,6 +217,9 @@ Provides:       compat-ath9k = 3.0
 %obsolete_kmp   ath3k 1.0_3
 Obsoletes:      ath3k-firmware <= 1.0
 Provides:       ath3k-firmware = 1.0
+%obsolete_kmp	compat-wireless 3.12
+%obsolete_kmp	rts5229 1.08
+%obsolete_kmp	rts_pstor 1.11
 
 # Provide the exported symbols as "ksym(symbol) = hash"
 %define __find_provides %_sourcedir/find-provides %name
@@ -292,14 +301,13 @@ if [ -f %_sourcedir/localversion ] ; then
     cat %_sourcedir/localversion > localversion
 fi
 
+cp %my_builddir/config/%cpu_arch_flavor .config
 if test -e %my_builddir/config.addon/%cpu_arch_flavor; then
 	# FIXME: config.addon doesn't affect the %CONFIG_ macros defined at
 	# the top of the specfile
-	%_sourcedir/configtool.pl %my_builddir/config{,.addon}/%cpu_arch_flavor >.config
-else
-	cp %my_builddir/config/%cpu_arch_flavor .config
+	../scripts/kconfig/merge_config.sh -m .config %my_builddir/config.addon/%cpu_arch_flavor
 fi
-%build_src_dir/scripts/config \
+../scripts/config \
 	--set-str CONFIG_LOCALVERSION -%source_rel-%build_flavor \
 	--enable  CONFIG_SUSE_KERNEL \
 %if 0%{?__debug_package:1}
@@ -309,7 +317,7 @@ fi
 	--disable CONFIG_DEBUG_INFO
 %endif
 
-MAKE_ARGS="$MAKE_ARGS -C %build_src_dir O=$PWD"
+MAKE_ARGS="$MAKE_ARGS %{?_smp_mflags} -C .. O=$PWD"
 if test -e %_sourcedir/TOLERATE-UNKNOWN-NEW-CONFIG-OPTIONS; then
     yes '' | make oldconfig $MAKE_ARGS
 else
@@ -342,50 +350,37 @@ if test -e %my_builddir/kabi/%cpu_arch/symtypes-%build_flavor; then
     %_sourcedir/modversions --unpack . < $_
 fi
 
-# copy optional module signing files:
-# *.x509, *.crt
-#  - certificates with pubkeys used to verify module and firmware signatures
-#    at runtime. *.crt files assumed to be in the PEM format.
-# signing_key.priv
-#  - unencrypted private key used to sign modules and firmware during build
-# x509.genkey
-#  - openssl req config to generate a new signing_key.{x509,priv} pair for the
-#    build
-for f in %_sourcedir/*.x509 %_sourcedir/{signing_key.priv,x509.genkey}; do
-    if test -e "$f"; then
-        cp "$f" .
-    fi
-done
+# copy module signing certificate(s)
+found_sigkey=false
 for f in %_sourcedir/*.crt; do
     if ! test -e "$f"; then
         continue
     fi
-    out=${f##*/}
-    out=${out%.crt}.x509
-    openssl x509 -inform PEM -in "$f" -outform DER -out "$out"
+    if test "${f##*/}" = %CONFIG_MODULE_SIG_KEY; then
+        found_sigkey=true
+	cp "$f" .
+    else
+        cat "$f" >>keyring.crt
+    fi
 done
-# Convince kernel/Makefile not to generate a new keypair
-touch x509.genkey
-touch signing_key.x509
+if ! $found_sigkey; then
+    echo "warning: %CONFIG_MODULE_SIG_KEY not found"
+    # Let certs/Makefile generate a keypair
+    ../scripts/config --set-str CONFIG_MODULE_SIG_KEY "certs/signing_key.pem"
+fi
+if test -s keyring.crt; then
+    ../scripts/config --set-str SYSTEM_TRUSTED_KEYS_FILENAME "keyring.crt"
+fi
 
-# The %{_smp_mflags} macro is defined to a number, make will spawn that many jobs.
-# There are several ways how to define it:
-# If you are using the build script:
-#     build --jobs=N kernel-$flavor.spec
-# With plain rpmbuild:
-#     rpmbuild -ba --define 'jobs N' kernel-$flavor.spec
-# To spawn as many jobs as there are cpu cores:
-#     rpmbuild -ba --define "%_smp_mflags -j 0$(grep -Ec 'cpu[0-9]' /proc/stat)" \
-#         kernel-$flavor.spec
-# You can also set this permanently in ~/.rpmmacros:
-#     %_smp_mflags -j 0%(grep -Ec 'cpu[0-9]' /proc/stat)
+MAKE_ARGS="$MAKE_ARGS %{?_smp_mflags}"
+
 %if %CONFIG_KMSG_IDS == "y"
     chmod +x ../scripts/kmsg-doc
     MAKE_ARGS="$MAKE_ARGS D=2"
 %endif
 
 while true; do
-    make %{?_smp_mflags} all $MAKE_ARGS CONFIG_DEBUG_SECTION_MISMATCH=y 2>&1 \
+    make all $MAKE_ARGS 2>&1 \
         | tee buildlog
     if test "${PIPESTATUS[0]}" -eq 0; then
         break
@@ -460,9 +455,6 @@ add_vmlinux()
 %ifarch %ix86 x86_64
     add_vmlinux --compressed
     image=bzImage
-%if %build_xen
-    test -f arch/x86/boot/$image || image=vmlinuz
-%endif
     cp -p arch/x86/boot/$image %buildroot/boot/vmlinuz-%kernelrelease-%build_flavor
     image=vmlinuz
 %endif
@@ -526,6 +518,10 @@ for sub in '-base' '' '-extra'; do
     *) base_package=0 ;;
     esac
     for script in preun postun pre post devel-pre devel-post; do
+        if test %build_flavor = "zfcpdump"; then
+            : >%my_builddir/$script$sub.sh
+            continue
+        fi
         sed -e "s:@KERNELRELEASE@:%kernelrelease:g" \
             -e "s:@IMAGE@:$image:g" \
             -e "s:@FLAVOR""@:%build_flavor:g" \
@@ -553,7 +549,7 @@ for sub in '-base' '' '-extra'; do
     done
 done
 
-%if %build_xen || %build_vanilla
+%if %build_vanilla
 # keep this -suffix list in sync with post.sh and postun.sh
 suffix=-%build_flavor
 %endif
@@ -705,7 +701,7 @@ if [ %CONFIG_MODULES = y ]; then
             esac
         done
     # Recreate the generated Makefile with correct path
-    sh ../scripts/mkmakefile ../../../linux-%kernelrelease%variant \
+    sh ../scripts/mkmakefile ../../../%{basename:%src_install_dir} \
         %rpm_install_dir/%cpu_arch_flavor \
         $(echo %srcversion | sed -r 's/^([0-9]+)\.([0-9]+).*/\1 \2/')
 fi
@@ -771,7 +767,7 @@ done | add_dirs_to_filelist >%my_builddir/kernel-devel.files
 	       -o -name '*.ko' -prune -o -type f -printf '/%%p\n'
 	cat %my_builddir/base-modules
     fi
-    if test %CONFIG_MODULE_SIG = "y"; then
+    if test %CONFIG_MODULE_SIG = "y" -a -d etc/uefi/certs; then
         find etc/uefi/certs -type f -printf '/%%p\n'
     fi
     test -d lib/firmware/%kernelrelease-%build_flavor && \
@@ -826,6 +822,7 @@ Requires(post): modutils
 Requires(post): perl-Bootloader
 Requires(post): mkinitrd
 @PROVIDES_OBSOLETES_BASE@
+%obsolete_rebuilds %name-base
 %ifarch %ix86
 Conflicts:      libc.so.6()(64bit)
 %endif
@@ -864,6 +861,7 @@ Requires(post): modutils
 Requires(post): perl-Bootloader
 Requires(post): mkinitrd
 @PROVIDES_OBSOLETES_EXTRA@
+%obsolete_rebuilds %name-extra
 Supplements:    packageand(product(SUSE_SLED):%{name}_%_target_cpu)
 %ifarch %ix86
 Conflicts:      libc.so.6()(64bit)
@@ -912,9 +910,15 @@ Summary:        Development files necessary for building kernel modules
 Group:          Development/Sources
 Provides:       %name-devel = %version-%source_rel
 Provides:       multiversion(kernel)
+%if ! %build_vanilla
 Requires:       kernel-devel%variant = %version-%source_rel
 Supplements:    packageand(%name:kernel-devel%variant)
+%else
+Requires:       kernel-source-vanilla = %version-%source_rel
+Supplements:    packageand(%name:kernel-source-vanilla)
+%endif
 @PROVIDES_OBSOLETES_DEVEL@
+%obsolete_rebuilds %name-devel
 PreReq:         coreutils
 
 %description devel
